from django.urls import path

from .views import *

urlpatterns = [
    path("login/", LoginView.as_view(), name="operations-login"),
    path("dev/clear-data/", ClearDevelopmentDataView.as_view(), name="operations-clear-development-data"),
    path("overview/", OverviewView.as_view(), name="operations-overview"),
    path("reservations/", ReservationListView.as_view(), name="operations-reservations"),
    path("reservations/<uuid:reservation_id>/", ReservationDetailView.as_view()),
    path("reservations/<uuid:reservation_id>/manual-payment/", ManualPaymentView.as_view()),
    path("reservations/<uuid:reservation_id>/cancel/", CancelReservationView.as_view()),
    path("expeditions/", ExpeditionListCreateView.as_view(), name="operations-expeditions"),
    path("expeditions/<uuid:pk>/", ExpeditionDetailView.as_view(), name="operations-expedition-detail"),
    path("lodges/", LodgeListCreateView.as_view(), name="operations-lodges"),
    path("lodges/<uuid:pk>/", LodgeDetailView.as_view(), name="operations-lodge-detail"),
    path("rivers/", RiverListCreateView.as_view(), name="operations-rivers"),
    path("rivers/<uuid:pk>/", RiverDetailView.as_view(), name="operations-river-detail"),
    path("rivers/<uuid:river_id>/species/", RiverSpeciesView.as_view(), name="operations-river-species"),
    path("amenities/", AmenityListView.as_view(), name="operations-amenities"),
    path("all-inclusive-packages/", AllInclusivePackageListCreateView.as_view(), name="operations-all-inclusive-packages"),
    path("all-inclusive-packages/<uuid:pk>/", AllInclusivePackageDetailView.as_view(), name="operations-all-inclusive-package-detail"),
    path("beverage-packages/", BeveragePackageListCreateView.as_view(), name="operations-beverage-packages"),
    path("beverage-packages/<uuid:pk>/", BeveragePackageDetailView.as_view(), name="operations-beverage-package-detail"),
    path("beverage-packages/<uuid:package_id>/items/", BeveragePackageItemView.as_view(), name="operations-beverage-package-items"),
    path("products/", ProductListView.as_view(), name="operations-products"),
    path("species/", SpeciesListCreateView.as_view(), name="operations-species"),
    path("species/<str:slug>/", SpeciesDetailView.as_view(), name="operations-species-detail"),
    path("reservations/<uuid:reservation_id>/participants/<uuid:participant_id>/", ParticipantUpdateView.as_view(), name="operations-participant-update"),
    path("expeditions/<uuid:expedition_id>/manifest/", ExpeditionManifestView.as_view(), name="operations-expedition-manifest"),
    path("expeditions/<uuid:expedition_id>/manifest.csv", ExpeditionManifestCsvView.as_view(), name="operations-expedition-manifest-csv"),
    path("expeditions/<uuid:expedition_id>/configuration/", ExpeditionConfigurationView.as_view()),
    path("expeditions/<uuid:expedition_id>/consolidation/", ConsolidationView.as_view()),
    path("expeditions/<uuid:expedition_id>/consolidation.csv", ConsolidationCsvView.as_view()),
    path("expeditions/<uuid:expedition_id>/consolidation.txt", ConsolidationTxtView.as_view()),
    path("gear-products/", FishingGearProductListCreateView.as_view(), name="operations-gear-products"),
    path("gear-products/<uuid:pk>/", FishingGearProductDetailView.as_view(), name="operations-gear-product-detail"),
    path("reservations/<uuid:reservation_id>/gear-addons/", ReservationGearAddonView.as_view(), name="operations-reservation-gear-addons"),
    path("reservations/<uuid:reservation_id>/gear-addons/<uuid:addon_id>/", ReservationGearAddonDetailView.as_view(), name="operations-reservation-gear-addon-detail"),
    path("customers/", CustomerListView.as_view(), name="operations-customers"),
    path("customers/<uuid:customer_id>/", CustomerDetailView.as_view(), name="operations-customer-detail"),
]
