# Generated by Django 6.0.8 on 2026-08-26 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_count', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('HELD', 'Vagas protegidas'), ('AWAITING_PAYMENT', 'Aguardando pagamento'), ('PARTIALLY_PAID', 'Parcialmente paga'), ('CONFIRMED', 'Confirmada'), ('PAID', 'Paga'), ('EXPIRED', 'Expirada'), ('CANCELLED', 'Cancelada'), ('REFUNDED', 'Reembolsada')], default='HELD', max_length=24)),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('total_price_cents', models.PositiveIntegerField()),
                ('deposit_cents', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='customers.customer')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='expeditions.expedition')),
            ],
            options={
                'indexes': [models.Index(fields=['expedition', 'status', 'held_until'], name='reservation_expedit_5bb3d7_idx')],
            },
        ),
    ]
