# Generated by Django 6.0.8 on 2026-08-26 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservationparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='balance_due_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_plan',
            field=models.CharField(choices=[('DEPOSIT', 'Sinal'), ('FULL', 'Integral')], default='DEPOSIT', max_length=12),
        ),
        migrations.CreateModel(
            name='ReservationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('actor_type', models.CharField(choices=[('SYSTEM', 'Sistema'), ('CUSTOMER', 'Cliente'), ('ADMIN', 'Administrador'), ('PROVIDER', 'Provedor')], default='SYSTEM', max_length=20)),
                ('actor_identifier', models.CharField(blank=True, max_length=160)),
                ('previous_status', models.CharField(blank=True, max_length=24)),
                ('new_status', models.CharField(blank=True, max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reservations.reservation')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['reservation', 'created_at'], name='reservation_reserva_27ce37_idx')],
            },
        ),
    ]
