# Generated by Django 6.0.8 on 2026-08-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_balance_due_at_reservation_payment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationparticipant',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='onboarding_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em preenchimento'), ('COMPLETED', 'Completo')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='operational_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
