# Generated by Django 6.0.8 on 2026-09-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservationparticipant_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='beverage_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
