# Generated by Django 6.0.8 on 2026-09-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0003_product_expedition_meeting_instructions_and_more'),
        ('reservations', '0005_reservation_beverage_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('requires_details', models.BooleanField(default=False)),
                ('is_none', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='dietary_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='dietary_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='product_choices_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ParticipantChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_completions', to='expeditions.checklistitem')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_completions', to='reservations.reservationparticipant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'item'), name='unique_participant_checklist_completion')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantDietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_restrictions', to='reservations.reservationparticipant')),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_links', to='reservations.dietaryrestriction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'restriction'), name='unique_participant_dietary_restriction')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantProductChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expedition_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_choices', to='expeditions.expeditionproduct')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_choices', to='reservations.reservationparticipant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'expedition_product'), name='unique_participant_product_choice')],
            },
        ),
    ]
