# Generated by Django 6.0.8 on 2026-09-18 18:31

from django.db import migrations, models


KNOWN_ALIASES = {"heineken", "cerveja_heineken", "cerveja_sem_alcool", "heineken_zero", "agua_sem_gas", "agua", "agua_com_gas", "refrigerante", "refri", "suco"}


def mark_ambiguous_legacy(apps, schema_editor):
    Reservation = apps.get_model("reservations", "Reservation")
    for reservation in Reservation.objects.exclude(beverage_preferences={}):
        legacy = reservation.beverage_preferences or {}
        beverages = legacy.get("beverages", {}) or {}
        positive_keys = {key for key, value in beverages.items() if isinstance(value, (int, float)) and value > 0}
        has_legacy = bool(positive_keys or str(legacy.get("dietary_restrictions", "")).strip())
        ambiguous = has_legacy and (reservation.participants.count() != 1 or bool(positive_keys - KNOWN_ALIASES))
        if reservation.legacy_preferences_review_required != ambiguous:
            reservation.legacy_preferences_review_required = ambiguous
            reservation.save(update_fields=("legacy_preferences_review_required",))


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_seed_catalog_and_migrate_legacy_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='legacy_preferences_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_ambiguous_legacy, migrations.RunPython.noop),
    ]
