# Generated by Django 6.0.8 on 2026-09-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservation_legacy_preferences_review_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationparticipant',
            name='health_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='vest_size',
            field=models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('EXG', 'EXG')], default='G', max_length=10),
        ),
    ]
