# Generated by Django 6.0.8 on 2026-10-02 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0012_fishinggearproduct'),
        ('reservations', '0009_reservationparticipant_health_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationGearAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modality', models.CharField(max_length=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('total_price_cents', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gear_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addons', to='expeditions.fishinggearproduct')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear_addons', to='reservations.reservationparticipant')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_addons', to='reservations.reservation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
