"use client";
import Link from "next/link";
import { FormEvent,useCallback,useEffect,useState } from "react";
import {AlertCircle,CalendarDays,Check,CheckCircle2,ClipboardCheck,Clock3,GlassWater,MapPin,MessageCircle,WalletCards} from "lucide-react";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000/api";
type Offer={id:string;name?:string;product_name?:string;category?:string;active?:boolean};
type Item={id:string;title:string;description?:string;required?:boolean;active?:boolean};
type Person={id:string;full_name:string;onboarding_status?:string;selected_offer_ids?:string[];no_beverages?:boolean;preferences_confirmed?:boolean;dietary_restriction_codes?:string[];dietary_details?:string;completed_item_ids?:string[]};
type EventItem={type:string;created_at:string}; type Data={id:string;reference:string;status:string;total_price_cents:number;paid_amount_cents:number;remaining_balance_cents:number;balance_due_at:string|null;participants:Person[];offers?:Offer[];checklist_items?:Item[];notices?:string[];whatsapp_url?:string;events?:EventItem[];onboarding:{completed:number;total:number;steps:Record<string,boolean>};expedition:{name:string;slug:string;destination:string;departure_location?:string;meeting_instructions?:string;starts_at:string;ends_at:string;offers?:Offer[];checklist_items?:Item[]}};
const restrictions=[["none","Sem restrições"],["vegetarian","Vegetariano"],["vegan","Vegano"],["lactose","Intolerância à lactose"],["gluten","Restrição a glúten"],["allergy","Alergia alimentar"],["other","Outros"]];
const money=(v:number)=>(v/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const date=(v:string)=>new Date(`${v}T12:00`).toLocaleDateString("pt-BR");
const headers=()=>({Authorization:`Bearer ${sessionStorage.getItem("customer-session-token")??""}`});
async function result(r:Response){const body=await r.json().catch(()=>({}));if(!r.ok)throw body;return body}
function error(v:unknown){if(v&&typeof v==="object")return Object.values(v as Record<string,unknown>).flat().join(" ");return "Não foi possível concluir."}
export function CustomerJourney({reservationId,confirmation=false}:{reservationId:string;confirmation?:boolean}){
 const [data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(true),[failure,setFailure]=useState(""),[personId,setPersonId]=useState("");
 const load=useCallback(async()=>{setBusy(true);setFailure("");try{if(!sessionStorage.getItem("customer-session-token"))throw {detail:"Sua sessão não foi encontrada."};const d=await result(await fetch(`${API}/me/reservations/${reservationId}/`,{headers:headers()})) as Data;setData(d);setPersonId(x=>x||d.participants[0]?.id||"")}catch(e){setFailure(error(e))}finally{setBusy(false)}},[reservationId]);useEffect(()=>{const task=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(task)},[load]);
 if(busy)return <State text="Carregando sua expedição..."/>;if(!data)return <State text={failure}/>;
 const person=data.participants.find(p=>p.id===personId)??data.participants[0], offers=(data.offers??data.expedition.offers??[]).filter(x=>x.active!==false),items=(data.checklist_items??data.expedition.checklist_items??[]).filter(x=>x.active!==false),temporal=temporalState(data.expedition.starts_at,data.expedition.ends_at),notices=data.notices?.length?data.notices:derivedNotices(data),progress=data.onboarding.total?Math.round(data.onboarding.completed/data.onboarding.total*100):0;
 return <section className="container-page pb-16"><header className="rounded-2xl bg-brand-900 p-7 text-white"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-sand-200">{confirmation?"Reserva confirmada":"Minha Expedição"}</p><h1 className="mt-2 text-4xl font-black">{data.expedition.name}</h1><p className="mt-2 flex gap-2 text-white/75"><MapPin className="size-5"/>{data.expedition.destination}</p></div><div className="rounded-xl bg-white/10 px-5 py-3 text-center"><strong className="block text-2xl">{temporal.title}</strong><span className="text-sm text-white/75">{temporal.copy}</span></div></div></header>
 {notices.map(n=><p key={n} className="mt-3 flex gap-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><AlertCircle className="size-5 shrink-0"/>{n}</p>)}
 <div className="mt-6 grid gap-4 md:grid-cols-3"><Card title="Reserva" icon={CalendarDays}><Rows values={[["Referência",`#${data.reference}`],["Status",data.status],["Período",`${date(data.expedition.starts_at)} a ${date(data.expedition.ends_at)}`],["Embarque",data.expedition.departure_location??"A confirmar"]]}/>{data.expedition.meeting_instructions&&<p className="mt-4 rounded-lg bg-gray-50 p-3 text-sm"><strong className="block">Orientações do encontro</strong>{data.expedition.meeting_instructions}</p>}</Card><Card title="Financeiro" icon={WalletCards}><Rows values={[["Total",money(data.total_price_cents)],["Pago",money(data.paid_amount_cents)],["Saldo",money(data.remaining_balance_cents)],["Vencimento",data.balance_due_at?date(data.balance_due_at):"Quitado"]]}/>{data.remaining_balance_cents>0&&<Payment id={data.id} amount={data.remaining_balance_cents} saved={setData}/>}</Card><Card title="Atendimento" icon={MessageCircle}><p className="text-sm text-ink-500">Precisa ajustar algum detalhe da viagem?</p><a href={data.whatsapp_url??process.env.NEXT_PUBLIC_WHATSAPP_URL??"https://wa.me/5562981612128"} className="mt-4 block rounded-lg border border-brand-600 p-3 text-center font-bold text-brand-700">Falar com a equipe</a></Card></div>
 <h2 className="mt-8 text-2xl font-black">Preparação individual</h2><p className="text-sm text-ink-500">Cada viajante tem escolhas e checklist próprios.</p><div className="mt-4 flex gap-2 overflow-auto">{data.participants.map(p=><button key={p.id} onClick={()=>setPersonId(p.id)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold ${p.id===person?.id?"bg-brand-700 text-white":"border bg-white"}`}>{p.full_name}</button>)}</div>
 {person&&<><Card title="Progresso da preparação" icon={CheckCircle2}><div className="flex justify-between text-sm"><span>Etapas concluídas</span><strong>{data.onboarding.completed} de {data.onboarding.total} · {progress}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full bg-brand-600" style={{width:`${progress}%`}}/></div><div className="mt-4 grid gap-2 sm:grid-cols-5">{Object.entries(data.onboarding.steps).map(([step,done])=><div key={step} className={`rounded-lg p-2 text-center text-xs font-bold ${done?"bg-brand-50 text-brand-800":"bg-gray-50 text-ink-500"}`}>{done?"✓ ":""}{stepLabel(step)}</div>)}</div></Card><div className="mt-4 grid gap-4 lg:grid-cols-2"><Preferences key={`p-${person.id}`} id={data.id} person={person} offers={offers} saved={setData}/><Checklist key={`c-${person.id}`} id={data.id} person={person} items={items} saved={setData}/></div>{!!data.events?.length&&<Card title="Histórico da reserva" icon={Clock3}><div className="divide-y">{data.events.map((event,index)=><div key={`${event.type}-${index}`} className="flex justify-between gap-3 py-3 text-sm"><span>{eventLabel(event.type)}</span><time className="text-ink-500">{new Date(event.created_at).toLocaleDateString("pt-BR")}</time></div>)}</div></Card>}</>}
 {confirmation&&<div className="mt-6 text-center"><Link href={`/expedicoes/${data.expedition.slug}/minha-expedicao/${data.id}` as never} className="inline-block rounded-lg bg-brand-600 px-6 py-3 font-bold text-white">Abrir Minha Expedição</Link></div>}</section>
}
function Preferences({id,person,offers,saved}:{id:string;person:Person;offers:Offer[];saved:(d:Data)=>void}){const [chosen,setChosen]=useState(person.selected_offer_ids??[]),[none,setNone]=useState(!!person.no_beverages),[codes,setCodes]=useState(person.dietary_restriction_codes??[]),[details,setDetails]=useState(person.dietary_details??""),[failure,setFailure]=useState(""),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(!none&&!chosen.length)return setFailure("Escolha uma bebida ou confirme que não deseja nenhuma.");if(!codes.length)return setFailure("Informe as restrições ou confirme “Sem restrições”.");if(codes.includes("other")&&!details.trim())return setFailure("Descreva a opção Outros.");setBusy(true);try{saved(await result(await fetch(`${API}/me/reservations/${id}/participants/${person.id}/preferences/`,{method:"PUT",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({selected_offer_ids:none?[]:chosen,no_beverages:none,dietary_restriction_codes:codes,dietary_details:details})})))}catch(x){setFailure(error(x))}finally{setBusy(false)}}return <Card title="Bebidas e alimentação" icon={GlassWater}><form onSubmit={submit}><p className="text-sm text-ink-500">Escolha opções, sem informar unidades.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{offers.map(o=><button type="button" disabled={none} key={o.id} onClick={()=>setChosen(c=>c.includes(o.id)?c.filter(x=>x!==o.id):[...c,o.id])} className={`flex gap-2 rounded-lg border p-3 text-left ${chosen.includes(o.id)?"border-brand-600 bg-brand-50":""}`}><Check className={`size-5 ${chosen.includes(o.id)?"opacity-100":"opacity-15"}`}/><span className="text-sm font-bold">{o.product_name??o.name}</span></button>)}</div><label className="mt-3 flex gap-2 rounded-lg border p-3 text-sm font-bold"><input type="checkbox" checked={none} onChange={e=>{setNone(e.target.checked);if(e.target.checked)setChosen([])}}/>Não quero nenhuma bebida</label><h3 className="mt-5 font-black">Restrições</h3><div className="mt-2 flex flex-wrap gap-2">{restrictions.map(([code,label])=><button type="button" key={code} onClick={()=>setCodes(c=>code==="none"?["none"]:c.includes(code)?c.filter(x=>x!==code):[...c.filter(x=>x!=="none"),code])} className={`rounded-full border px-3 py-2 text-sm ${codes.includes(code)?"bg-brand-50 text-brand-800":""}`}>{label}</button>)}</div><textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="Detalhes e cuidados" className="mt-3 min-h-20 w-full rounded-lg border p-3"/><Save busy={busy} failure={failure}/></form></Card>}
function Checklist({id,person,items,saved}:{id:string;person:Person;items:Item[];saved:(d:Data)=>void}){const [done,setDone]=useState(person.completed_item_ids??[]),[busy,setBusy]=useState(false),[failure,setFailure]=useState("");async function save(){setBusy(true);try{saved(await result(await fetch(`${API}/me/reservations/${id}/participants/${person.id}/checklist/`,{method:"PUT",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({completed_item_ids:done})})))}catch(x){setFailure(error(x))}finally{setBusy(false)}}return <Card title="Checklist individual" icon={ClipboardCheck}><div className="space-y-2">{items.map(i=><label key={i.id} className="flex gap-3 rounded-lg border p-3"><input type="checkbox" checked={done.includes(i.id)} onChange={()=>setDone(c=>c.includes(i.id)?c.filter(x=>x!==i.id):[...c,i.id])}/><span><strong className="text-sm">{i.title}{i.required&&" · obrigatório"}</strong><small className="block text-ink-500">{i.description}</small></span></label>)}{!items.length&&<p className="text-sm text-ink-500">Checklist ainda não publicado.</p>}</div><Save busy={busy} failure={failure} click={()=>void save()}/></Card>}
function Payment({id,amount,saved}:{id:string;amount:number;saved:(d:Data)=>void}){const [charge,setCharge]=useState<{id:string}|null>(null),[busy,setBusy]=useState(false),[failure,setFailure]=useState("");async function call(confirm=false){setBusy(true);try{const d=await result(await fetch(`${API}/me/reservations/${id}/balance-payment/${confirm?"confirm/":""}`,{method:"POST",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify(confirm?{payment_id:charge?.id}:{})}));if(confirm)saved(d);else setCharge(d)}catch(x){setFailure(error(x))}finally{setBusy(false)}}return <div className="mt-4"><button onClick={()=>void call(!!charge)} disabled={busy} className="w-full rounded-lg bg-brand-600 p-3 font-bold text-white">{busy?"Processando...":charge?"Simular confirmação":`Pagar ${money(amount)}`}</button>{failure&&<p className="mt-2 text-xs text-red-700">{failure}</p>}</div>}
function Card({title,icon:Icon,children}:{title:string;icon:typeof CalendarDays;children:React.ReactNode}){return <article className="rounded-xl border bg-white p-5"><h2 className="flex gap-2 text-lg font-black"><Icon className="text-brand-700"/>{title}</h2><div className="mt-4">{children}</div></article>}function Rows({values}:{values:string[][]}){return <div className="space-y-3 text-sm">{values.map(v=><div key={v[0]} className="flex justify-between gap-3"><span className="text-ink-500">{v[0]}</span><strong className="text-right">{v[1]}</strong></div>)}</div>}function Save({busy,failure,click}:{busy:boolean;failure:string;click?:()=>void}){return <div className="mt-4">{failure&&<p className="mb-2 text-sm text-red-700">{failure}</p>}<button type={click?"button":"submit"} onClick={click} disabled={busy} className="w-full rounded-lg bg-brand-600 p-3 font-bold text-white">{busy?"Salvando...":"Salvar"}</button></div>}function State({text}:{text:string}){return <section className="container-page min-h-[50vh] py-16 text-center text-ink-500">{text}</section>}
function temporalState(starts:string,ends:string){const now=Date.now(),start=new Date(`${starts}T00:00:00`).getTime(),end=new Date(`${ends}T23:59:59`).getTime();if(now>end)return{title:"Concluída",copy:"Esta expedição já terminou"};if(now>=start)return{title:"Em andamento",copy:"A aventura começou"};const days=Math.ceil((start-now)/86400000);return{title:String(days),copy:days===1?"dia para a viagem":"dias para a viagem"}}
function derivedNotices(data:Data){const values:string[]=[];if(data.remaining_balance_cents>0){const overdue=data.balance_due_at&&new Date(`${data.balance_due_at}T23:59:59`).getTime()<Date.now();values.push(overdue?"O saldo da reserva está vencido. O pagamento simulado continua disponível.":"Há saldo pendente nesta reserva.")}if(data.onboarding.completed<data.onboarding.total)values.push("Ainda há etapas de preparação pendentes.");const days=Math.ceil((new Date(`${data.expedition.starts_at}T00:00:00`).getTime()-Date.now())/86400000);if(days>=0&&days<=7)values.push("A expedição está próxima. Revise encontro, documentos e checklist.");return values}
function stepLabel(value:string){return({payment:"Pagamento",participants:"Cadastros",preferences:"Bebidas",dietary_restrictions:"Alimentação",checklist:"Checklist"} as Record<string,string>)[value]??value}
function eventLabel(value:string){return({RESERVATION_HELD:"Reserva criada",PAYMENT_CONFIRMED:"Pagamento confirmado",PREFERENCES_UPDATED:"Preferências atualizadas",CHECKLIST_UPDATED:"Checklist atualizado",RESERVATION_CANCELLED:"Reserva cancelada"} as Record<string,string>)[value]??"Atualização da reserva"}
