# Generated by Django 6.0.8 on 2026-08-26 02:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('destination', models.CharField(max_length=160)),
                ('departure_location', models.CharField(blank=True, max_length=160)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('price_per_person_cents', models.PositiveIntegerField()),
                ('deposit_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicada'), ('SOLD_OUT', 'Esgotada'), ('CLOSED', 'Encerrada'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('starts_at',),
            },
        ),
    ]
