# Generated by Django 6.0.8 on 2026-08-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='balance_due_days_before',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
