# Generated by Django 6.0.8 on 2026-09-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0002_expedition_balance_due_days_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(default='BEBIDA', max_length=60)),
                ('unit', models.CharField(choices=[('unidade', 'Unidade'), ('lata', 'Lata'), ('garrafa', 'Garrafa'), ('pacote', 'Pacote'), ('saco', 'Saco')], max_length=20)),
                ('package_size', models.PositiveIntegerField(blank=True, null=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='expedition',
            name='meeting_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_items', to='expeditions.expedition')),
            ],
            options={
                'ordering': ('display_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ExpeditionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_quantity_per_participant', models.PositiveIntegerField(default=1)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_offers', to='expeditions.expedition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedition_offers', to='expeditions.product')),
            ],
            options={
                'ordering': ('display_order', 'product__name'),
                'constraints': [models.UniqueConstraint(fields=('expedition', 'product'), name='unique_expedition_product')],
            },
        ),
    ]
