# Generated by Django 6.0.8 on 2026-09-18 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0003_product_expedition_meeting_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionConfigurationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('actor_identifier', models.CharField(blank=True, max_length=160)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_events', to='expeditions.expedition')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
