# Generated by Django 6.0.8 on 2026-09-19 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0004_expeditionconfigurationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('river_section', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('meeting_point', models.CharField(blank=True, max_length=200)),
                ('directions', models.TextField(blank=True)),
                ('cover_image_url', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TargetSpecies',
            fields=[
                ('slug', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('COURO', 'Peixe de Couro'), ('ESCAMA', 'Peixe de Escama')], default='COURO', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('category', 'common_name'),
            },
        ),
        migrations.AddField(
            model_name='expedition',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='expedition',
            name='gallery_image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expedition',
            name='inclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expedition',
            name='lodge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expeditions', to='expeditions.lodge'),
        ),
        migrations.CreateModel(
            name='ExpeditionSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_species', to='expeditions.expedition')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expeditions', to='expeditions.targetspecies')),
            ],
            options={
                'ordering': ('-is_primary', 'display_order', 'species__common_name'),
            },
        ),
        migrations.AddField(
            model_name='expedition',
            name='target_species',
            field=models.ManyToManyField(blank=True, related_name='expedition_targets', through='expeditions.ExpeditionSpecies', to='expeditions.targetspecies'),
        ),
        migrations.AddConstraint(
            model_name='expeditionspecies',
            constraint=models.UniqueConstraint(fields=('expedition', 'species'), name='unique_expedition_species'),
        ),
    ]
