# Generated by Django 6.0.8 on 2026-10-01 21:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0007_update_species_products_and_inclusions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('FISHING_STRUCTURE', 'Estrutura Náutica e Pesca'), ('ROOM_COMFORT', 'Acomodação e Conforto'), ('LEISURE', 'Lazer e Bem-estar'), ('GASTRONOMY', 'Culinária e Bar'), ('CONNECTIVITY', 'Conectividade e Apoio')], max_length=30)),
                ('icon_key', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('category', 'display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('basin', models.CharField(choices=[('TOCANTINS_ARAGUAIA', 'Bacia Tocantins-Araguaia'), ('AMAZONICA', 'Bacia Amazônica'), ('PRATA', 'Bacia do Prata / Pantanal'), ('SAO_FRANCISCO', 'Bacia do São Francisco')], default='TOCANTINS_ARAGUAIA', max_length=40)),
                ('states', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('regulations', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='lodge',
            name='boat_fleet_details',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LodgeAmenityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_highlight', models.BooleanField(default=False)),
                ('custom_note', models.CharField(blank=True, max_length=140)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_links', to='expeditions.amenity')),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_links', to='expeditions.lodge')),
            ],
        ),
        migrations.AddField(
            model_name='lodge',
            name='amenities_structured',
            field=models.ManyToManyField(blank=True, related_name='lodges', through='expeditions.LodgeAmenityLink', to='expeditions.amenity'),
        ),
        migrations.AddField(
            model_name='lodge',
            name='river',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lodges', to='expeditions.river'),
        ),
        migrations.CreateModel(
            name='RiverSpecies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_native', models.BooleanField(default=True)),
                ('is_trophy', models.BooleanField(default=False)),
                ('best_season', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('river', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='river_species', to='expeditions.river')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rivers', to='expeditions.targetspecies')),
            ],
            options={
                'ordering': ('species__category', 'species__common_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='lodgeamenitylink',
            constraint=models.UniqueConstraint(fields=('lodge', 'amenity'), name='unique_lodge_amenity'),
        ),
        migrations.AddConstraint(
            model_name='riverspecies',
            constraint=models.UniqueConstraint(fields=('river', 'species'), name='unique_river_species'),
        ),
    ]
