# Generated by Django on 2026-10-02

from django.db import migrations


def seed_packages_and_link_expeditions(apps, schema_editor):
    AllInclusivePackage = apps.get_model("expeditions", "AllInclusivePackage")
    BeveragePackage = apps.get_model("expeditions", "BeveragePackage")
    BeveragePackageItem = apps.get_model("expeditions", "BeveragePackageItem")
    Product = apps.get_model("expeditions", "Product")
    Expedition = apps.get_model("expeditions", "Expedition")

    # 1. Ensure required beverage products exist
    corona_long, _ = Product.objects.get_or_create(
        name="Cerveja Corona Extra (Long Neck)",
        defaults={"category": "BEBIDA", "unit": "garrafa", "active": True, "aliases": ["corona", "corona long", "corona ln"]}
    )
    corona_lata, _ = Product.objects.get_or_create(
        name="Cerveja Corona Extra (Lata)",
        defaults={"category": "BEBIDA", "unit": "lata", "active": True, "aliases": ["corona lata"]}
    )
    heineken_long, _ = Product.objects.get_or_create(
        name="Cerveja Heineken (Long Neck)",
        defaults={"category": "BEBIDA", "unit": "garrafa", "active": True, "aliases": ["heineken long", "heineken ln"]}
    )
    stella_long, _ = Product.objects.get_or_create(
        name="Cerveja Stella Artois (Long Neck)",
        defaults={"category": "BEBIDA", "unit": "garrafa", "active": True, "aliases": ["stella long", "stella ln"]}
    )
    antarctica_lata, _ = Product.objects.get_or_create(
        name="Cerveja Antarctica (Lata)",
        defaults={"category": "BEBIDA", "unit": "lata", "active": True, "aliases": ["antarctica", "antarctica lata", "boa"]}
    )

    # Fetch existing products
    stella = Product.objects.filter(name__icontains="Stella Artois").first() or stella_long
    heineken = Product.objects.filter(name="Cerveja Heineken").first() or heineken_long
    original = Product.objects.filter(name="Cerveja Original").first()
    coca = Product.objects.filter(name="Refrigerante Coca-Cola").first()
    coca_zero = Product.objects.filter(name="Refrigerante Coca-Cola Zero").first()
    guarana = Product.objects.filter(name="Refrigerante Guaraná Antarctica").first()
    agua = Product.objects.filter(name="Água sem gás").first()
    agua_gas = Product.objects.filter(name="Água com gás").first()
    suco = Product.objects.filter(name="Suco").first()

    # 2. Seed AllInclusivePackages
    pkg_regular, _ = AllInclusivePackage.objects.update_or_create(
        slug="estrutura-completa-regular",
        defaults={
            "name": "Estrutura Completa Regular (Sem Open Bar Alcoólico)",
            "description": "Estrutura premium completa de pesca esportiva no Araguaia. Hospedagem, combustível, iscas, guias e culinária inclusos; bebidas alcoólicas personalizadas ou sob demanda.",
            "inclusions": [
                "Hospedagem completa com café, almoço e jantar",
                "Combustível 100% incluso para todos os dias de pesca",
                "Guias nativos profissionais em barcos equipados com rádio VHF",
                "Iscas vivas e naturais inclusas",
                "Kit Sashimi & Ceviche preparado no rio",
                "Refrigerantes, água mineral e gelo à vontade",
                "Torneio esportivo entre duplas com troféus oficiais",
            ],
            "active": True,
        },
    )

    pkg_casais, _ = AllInclusivePackage.objects.update_or_create(
        slug="casais-vip-all-inclusive",
        defaults={
            "name": "All Inclusive Casais VIP (Tudo Incluso)",
            "description": "Experiência exclusiva para casais com suíte climatizada privativa, open bar premium, barco dedicado com piloteiro nativo e gastronomia especial no rio.",
            "inclusions": [
                "Suíte privativa climatizada com decoração especial para o casal",
                "Pensão completa com culinária regional e petiscaria no fim de tarde",
                "Open bar premium completo de cervejas (Stella Artois e Corona), drinks e refrigerantes",
                "Barco exclusivo para o casal com piloteiro nativo homologado",
                "Combustível 100% incluso sem limite de navegação",
                "Kit degustação e aperitivos ao pôr do sol no rio",
                "Iscas vivas selecionadas e tralhas de apoio à disposição",
                "Kit de boas-vindas especial da Expedição Piraíba",
            ],
            "active": True,
        },
    )

    pkg_tradicional, _ = AllInclusivePackage.objects.update_or_create(
        slug="tradicional-araguaia",
        defaults={
            "name": "All Inclusive Tradicional Araguaia",
            "description": "Pacote tradicional com tudo incluso: pensão completa, combustível livre, guias experientes e open bar completo de cervejas, refrigerantes e água.",
            "inclusions": [
                "Hospedagem com pensão completa (café da manhã, almoço e jantar)",
                "Combustível 100% livre para toda a jornada de pesca",
                "Barcos plataformados com motores potentes e guias nativos",
                "Iscas vivas da região e iscas naturais inclusas",
                "Open bar de cervejas, refrigerantes, água e gelo à vontade no barco e na pousada",
                "Petiscos no rio (sashimi de tucunaré / ceviche fresco)",
                "Troféus e premiação para os maiores exemplares capturados",
            ],
            "active": True,
        },
    )

    # 3. Seed BeveragePackages & Items
    bev_premium, _ = BeveragePackage.objects.update_or_create(
        slug="open-bar-premium",
        defaults={
            "name": "Open Bar Premium (Stella & Corona + Bebidas Suaves)",
            "description": "Seleção premium com Stella Artois, Corona Extra gelada, refrigerantes de primeira linha e águas minerais.",
            "active": True,
        },
    )
    premium_items = [
        (stella, 24, 1, "Cerveja oficial Stella Artois"),
        (corona_long, 24, 2, "Corona Extra Long Neck c/ limão"),
        (coca, 12, 3, "Coca-Cola lata gelada"),
        (guarana, 12, 4, "Guaraná Antarctica lata"),
        (agua, 24, 5, "Água mineral sem gás"),
        (agua_gas, 12, 6, "Água mineral com gás"),
    ]
    for prod, qty, order, note in premium_items:
        if prod:
            BeveragePackageItem.objects.update_or_create(
                package=bev_premium,
                product=prod,
                defaults={"standard_quantity_per_participant": qty, "display_order": order, "note": note},
            )

    bev_mix, _ = BeveragePackage.objects.update_or_create(
        slug="mix-tradicional-especial",
        defaults={
            "name": "Mix Cervejas Tradicionais & Especiais",
            "description": "Equilíbrio entre cervejas puro malte e clássicas brasileiras: Stella Artois, Heineken, Original, refrigerantes e água.",
            "active": True,
        },
    )
    mix_items = [
        (stella, 18, 1, "Stella Artois Puro Malte"),
        (heineken, 18, 2, "Heineken gelada"),
        (original, 12, 3, "Antarctica Original") if original else None,
        (coca, 12, 4, "Coca-Cola lata"),
        (guarana, 12, 5, "Guaraná Antarctica"),
        (agua, 24, 6, "Água mineral sem gás"),
    ]
    for entry in mix_items:
        if entry:
            prod, qty, order, note = entry
            BeveragePackageItem.objects.update_or_create(
                package=bev_mix,
                product=prod,
                defaults={"standard_quantity_per_participant": qty, "display_order": order, "note": note},
            )

    bev_sem_alcool, _ = BeveragePackage.objects.update_or_create(
        slug="sem-alcool-demanda",
        defaults={
            "name": "Sem Álcool / Sob Demanda (Refrigerantes, Águas e Sucos)",
            "description": "Foco em hidratação e bebidas suaves durante a pescaria. Bebidas alcoólicas adquiridas à parte ou trazidas pelos pescadores.",
            "active": True,
        },
    )
    sem_alcool_items = [
        (coca, 18, 1, "Coca-Cola tradicional"),
        (coca_zero, 12, 2, "Coca-Cola Zero açúcar") if coca_zero else None,
        (guarana, 18, 3, "Guaraná Antarctica"),
        (agua, 36, 4, "Água mineral sem gás"),
        (agua_gas, 18, 5, "Água mineral com gás"),
        (suco, 12, 6, "Sucos naturais e de frutas") if suco else None,
    ]
    for entry in sem_alcool_items:
        if entry:
            prod, qty, order, note = entry
            BeveragePackageItem.objects.update_or_create(
                package=bev_sem_alcool,
                product=prod,
                defaults={"standard_quantity_per_participant": qty, "display_order": order, "note": note},
            )

    # 4. Link existing expeditions without destructively altering inclusions or product offers
    for exp in Expedition.objects.all():
        if "casal" in exp.slug or "casais" in exp.slug:
            if not exp.all_inclusive_package:
                exp.all_inclusive_package = pkg_casais
            if not exp.beverage_package:
                exp.beverage_package = bev_premium
        else:
            if not exp.all_inclusive_package:
                exp.all_inclusive_package = pkg_regular
            if not exp.beverage_package:
                exp.beverage_package = bev_mix
        exp.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0010_add_packages_and_expedition_links'),
    ]

    operations = [
        migrations.RunPython(seed_packages_and_link_expeditions, reverse_func),
    ]
