# Generated by Django 6.0.8 on 2026-10-02 01:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0011_seed_packages_and_link_expeditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingGearProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('category', models.CharField(choices=[('HEAVY_ROD_REEL', 'Conjunto Pesado (Piraíba / Grandes Bagres)'), ('MEDIUM_ROD_REEL', 'Conjunto Médio (Pirarara / Tucunaré)'), ('TERMINAL_TACKLE', 'Acessórios e Terminais (Anzóis, Encastoados, Chumbadas)'), ('APPAREL', 'Vestuário UV, Bonés e Proteção'), ('SPECIALTY_BAIT', 'Iscas Especiais e Atrativos')], max_length=30)),
                ('modality', models.CharField(choices=[('RENTAL', 'Locação por Expedição'), ('SALE', 'Venda Direta'), ('BOTH', 'Venda ou Locação')], default='RENTAL', max_length=10)),
                ('technical_specs', models.JSONField(blank=True, default=dict)),
                ('rental_price_cents', models.PositiveIntegerField(default=0)),
                ('sale_price_cents', models.PositiveIntegerField(default=0)),
                ('inventory_quantity', models.PositiveSmallIntegerField(default=0)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('inventory_quantity__gte', 0)), name='gear_inventory_non_negative')],
            },
        ),
    ]
