# Generated by Django 6.0.8 on 2026-10-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0013_seed_gear_products_and_customer_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='target_species',
            field=models.ManyToManyField(blank=True, related_name='lodges', to='expeditions.targetspecies'),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='river_section',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
