# Generated by Django 6.0.8 on 2026-08-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationchallenge',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
