# Generated by Django 6.0.8 on 2026-10-02 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_verificationchallenge_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('rg_issuer', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('fishing_license_number', models.CharField(blank=True, max_length=50)),
                ('fishing_license_expiry', models.DateField(blank=True, null=True)),
                ('default_vest_size', models.CharField(blank=True, max_length=10)),
                ('dietary_notes', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=160)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('internal_admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='customers.customer')),
            ],
            options={
                'ordering': ('customer__full_name',),
            },
        ),
    ]
