# Generated by Django 6.0.8 on 2026-08-26 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_reservationparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='FAKE', max_length=30)),
                ('method', models.CharField(default='PIX', max_length=20)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('PAID', 'Pago'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20)),
                ('pix_copy_paste', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.payment')),
            ],
        ),
    ]
