# Generated by Django 6.0.8 on 2026-09-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('INITIAL', 'Pagamento inicial'), ('BALANCE', 'Saldo'), ('MANUAL', 'Manual')], default='INITIAL', max_length=20),
        ),
    ]
